import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1 },
  container: { flex: 1, padding: 16, paddingBottom: 32 },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    padding: 10,
    borderRadius: 8,
    marginBottom: 12,
  },
  chipScroll: { marginBottom: 10 },
  chip: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginRight: 8,
    borderRadius: 20,
    backgroundColor: "#eee",
    height: 40,
    justifyContent: "center",
  },
  chipSelected: { backgroundColor: "#007AFF" },
  chipText: { fontSize: 14 },
  chipTextSelected: { color: "white" },
  buttonContainer: { marginBottom: 20 },
  buttonPrimary: {
    padding: 14,
    backgroundColor: "#007AFF",
    borderRadius: 8,
    marginTop: 10,
  },
  buttonSuccess: {
    padding: 14,
    backgroundColor: "#34C759",
    borderRadius: 8,
    marginTop: 10,
  },
  buttonSecondary: {
    padding: 14,
    backgroundColor: "#FF9500",
    borderRadius: 8,
    marginTop: 10,
  },
  buttonText: { color: "white", textAlign: "center", fontWeight: "600" },
  card: {
    padding: 16,
    backgroundColor: "white",
    borderRadius: 10,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  cardTitle: { fontSize: 16, fontWeight: "bold" },
  header: { fontSize: 22, fontWeight: "bold", marginBottom: 12 },
  title: { fontSize: 24, fontWeight: "bold", marginBottom: 16 },
  tipCard: {
    backgroundColor: "#f0f9ff",
    padding: 16,
    borderRadius: 10,
    marginBottom: 12,
    borderLeftWidth: 5,
    borderLeftColor: "#007AFF",
  },
  tipTitle: { fontSize: 16, fontWeight: "bold", marginBottom: 4 },
  tipDescription: { fontSize: 14, color: "#333" },
});

